version: '3.9'

services:
  api:
    build: .
    ports:
      - 8008:8000
    command: uvicorn main:app --host 0.0.0.0 --reload
    depends_on:
      - redis
      - database

  redis:
    image: redis:latest

  database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=social_network_db
    ports:
      - 5432:5432
